FROM node:20-alpine

WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# We don't copy the rest of the code here because we will mount it as a volume in docker-compose
# This ensures hot-reloading works perfectly.

EXPOSE 3000

CMD ["npm", "run", "dev"]
