"""Add system_accounts table

Revision ID: 1e8fa1c232c9
Revises: 752d4ff38f7f
Create Date: 2026-07-01 20:42:00.698673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e8fa1c232c9'
down_revision: Union[str, Sequence[str], None] = '752d4ff38f7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_accounts',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_accounts_email'), 'system_accounts', ['email'], unique=True)
    op.create_index(op.f('ix_system_accounts_id'), 'system_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_system_accounts_username'), 'system_accounts', ['username'], unique=True)
    op.create_index(op.f('ix_system_accounts_uuid'), 'system_accounts', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_accounts_uuid'), table_name='system_accounts')
    op.drop_index(op.f('ix_system_accounts_username'), table_name='system_accounts')
    op.drop_index(op.f('ix_system_accounts_id'), table_name='system_accounts')
    op.drop_index(op.f('ix_system_accounts_email'), table_name='system_accounts')
    op.drop_table('system_accounts')
    # ### end Alembic commands ###
