"""Add KYC fields to owner and driver profiles

Revision ID: 2d9abe7e6072
Revises: 1e8fa1c232c9
Create Date: 2026-07-01 20:46:02.339996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d9abe7e6072'
down_revision: Union[str, Sequence[str], None] = '1e8fa1c232c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_profiles', sa.Column('kyc_status', sa.String(length=20), nullable=True))
    op.add_column('driver_profiles', sa.Column('driving_license_doc_url', sa.String(length=255), nullable=True))
    op.add_column('driver_profiles', sa.Column('background_check_doc_url', sa.String(length=255), nullable=True))
    op.add_column('driver_profiles', sa.Column('kyc_submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('driver_profiles', sa.Column('kyc_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('driver_profiles', sa.Column('kyc_rejection_reason', sa.String(length=500), nullable=True))
    op.add_column('owner_profiles', sa.Column('kyc_status', sa.String(length=20), nullable=True))
    op.add_column('owner_profiles', sa.Column('company_registration_doc_url', sa.String(length=255), nullable=True))
    op.add_column('owner_profiles', sa.Column('tax_doc_url', sa.String(length=255), nullable=True))
    op.add_column('owner_profiles', sa.Column('address_proof_url', sa.String(length=255), nullable=True))
    op.add_column('owner_profiles', sa.Column('kyc_submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('owner_profiles', sa.Column('kyc_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('owner_profiles', sa.Column('kyc_rejection_reason', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owner_profiles', 'kyc_rejection_reason')
    op.drop_column('owner_profiles', 'kyc_verified_at')
    op.drop_column('owner_profiles', 'kyc_submitted_at')
    op.drop_column('owner_profiles', 'address_proof_url')
    op.drop_column('owner_profiles', 'tax_doc_url')
    op.drop_column('owner_profiles', 'company_registration_doc_url')
    op.drop_column('owner_profiles', 'kyc_status')
    op.drop_column('driver_profiles', 'kyc_rejection_reason')
    op.drop_column('driver_profiles', 'kyc_verified_at')
    op.drop_column('driver_profiles', 'kyc_submitted_at')
    op.drop_column('driver_profiles', 'background_check_doc_url')
    op.drop_column('driver_profiles', 'driving_license_doc_url')
    op.drop_column('driver_profiles', 'kyc_status')
    # ### end Alembic commands ###
