"""Add passkey and pin tables

Revision ID: 2e4d23aafe76
Revises: 96baba7b2903
Create Date: 2026-07-02 18:37:32.261658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e4d23aafe76'
down_revision: Union[str, Sequence[str], None] = '96baba7b2903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_passkeys',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('credential_id', sa.String(length=255), nullable=False),
    sa.Column('public_key', sa.String(length=2048), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('transports', sa.String(length=255), nullable=True),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_passkeys_created_by'), 'user_passkeys', ['created_by'], unique=False)
    op.create_index(op.f('ix_user_passkeys_credential_id'), 'user_passkeys', ['credential_id'], unique=True)
    op.create_index(op.f('ix_user_passkeys_id'), 'user_passkeys', ['id'], unique=False)
    op.create_index(op.f('ix_user_passkeys_updated_by'), 'user_passkeys', ['updated_by'], unique=False)
    op.create_index(op.f('ix_user_passkeys_user_id'), 'user_passkeys', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_passkeys_uuid'), 'user_passkeys', ['uuid'], unique=True)
    op.create_table('user_quick_pin',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_quick_pin_created_by'), 'user_quick_pin', ['created_by'], unique=False)
    op.create_index(op.f('ix_user_quick_pin_id'), 'user_quick_pin', ['id'], unique=False)
    op.create_index(op.f('ix_user_quick_pin_updated_by'), 'user_quick_pin', ['updated_by'], unique=False)
    op.create_index(op.f('ix_user_quick_pin_user_id'), 'user_quick_pin', ['user_id'], unique=True)
    op.create_index(op.f('ix_user_quick_pin_uuid'), 'user_quick_pin', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_quick_pin_uuid'), table_name='user_quick_pin')
    op.drop_index(op.f('ix_user_quick_pin_user_id'), table_name='user_quick_pin')
    op.drop_index(op.f('ix_user_quick_pin_updated_by'), table_name='user_quick_pin')
    op.drop_index(op.f('ix_user_quick_pin_id'), table_name='user_quick_pin')
    op.drop_index(op.f('ix_user_quick_pin_created_by'), table_name='user_quick_pin')
    op.drop_table('user_quick_pin')
    op.drop_index(op.f('ix_user_passkeys_uuid'), table_name='user_passkeys')
    op.drop_index(op.f('ix_user_passkeys_user_id'), table_name='user_passkeys')
    op.drop_index(op.f('ix_user_passkeys_updated_by'), table_name='user_passkeys')
    op.drop_index(op.f('ix_user_passkeys_id'), table_name='user_passkeys')
    op.drop_index(op.f('ix_user_passkeys_credential_id'), table_name='user_passkeys')
    op.drop_index(op.f('ix_user_passkeys_created_by'), table_name='user_passkeys')
    op.drop_table('user_passkeys')
    # ### end Alembic commands ###
