"""Add missing identifier to otp_codes

Revision ID: 78f03d0408e5
Revises: e6f22aadcf9e
Create Date: 2026-07-02 06:58:18.658557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78f03d0408e5'
down_revision: Union[str, Sequence[str], None] = 'e6f22aadcf9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_codes', sa.Column('identifier', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otp_codes', 'identifier')
    # ### end Alembic commands ###
